fakhrialdariasky/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fakhrialdariaskyapp.urls')),
]

fakhrialdariaskyapp/urls.py
from django.urls import path

from . import views

app_name = 'fakhrialdariaskyapp'

urlpatterns = [
    path('', views.index, name='home'),
    path('story7', views.story7, name='story7'),
    path('story8', views.story8, name='story8'),
    path('api_buku', views.api_buku, name='api_buku'),
    path("login/", views.login_view, name = "login_view"),
    path("register/", views.register_view, name = 'register_view'),
    path("logout/", views.logout_view, name = "logout_view"),
    path("profile/<str:username>/", views.profile_view, name = "profile_view"),

]

fakhrialdariaskyapp/models.py
from django.db import models
from django.shortcuts import reverse
'''module for modeling the Post'''
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

#User
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.TextField()
    profile_picture_url = models.URLField(blank = True, default = "https://iupac.org/wp-content/uploads/2018/05/default-avatar-300x300.png")
    description = models.TextField(blank = True, default = "Hi! Ini profil kamu.")

    def __str__(self):
        return f"Profil {self.user.username}"

fakhrialdariaskyapp/forms.py
from django import forms

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User

class RegistrationForm(UserCreationForm):
    username = forms.CharField(label="Username", widget=forms.TextInput(attrs={
        "class" : "form-control mb-3",
        "placeholder" : "Username"
    }))

    password1 = forms.CharField(label="Password", widget=forms.TextInput(attrs={
        "class" : "form-control mb-3 ",
        "placeholder" : "Password",
        "type" : "password"
    }))

    password2 = forms.CharField(label="Konfirmasi password", widget=forms.TextInput(attrs={
        "class" : "form-control mb-3",
        "placeholder" : "Konfirmasi password",
        "type" : "password"
    }))

    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username", widget=forms.TextInput(attrs={
        "class" : "form-control mb-3",
        "placeholder" : "Username"
    }))

    password = forms.CharField(label="Password", widget=forms.TextInput(attrs={
        "class" : "form-control mb-3",
        "placeholder" : "Password",
        "type" : "password"
    }))

    class Meta:
        fields = "__all__"

fakhrialdariaskyapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from datetime import datetime, date
import urllib3
import json
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from .forms import RegistrationForm, LoginForm, AuthenticationForm
from .models import Profile


# Create your views here.
def index(request):
    return render(request, 'main/home.html')

def story7(request):
    return render(request, 'main/story7.html')

def story8(request):
    return render(request, 'main/story8.html')

def api_buku(request):
    http = urllib3.PoolManager()
    response = http.request(
        "GET", "https://www.googleapis.com/books/v1/volumes?q=" + request.GET.get('q', ''))
    return JsonResponse(json.loads(response.data.decode('utf8')))

def register_view(request):
    if request.user.is_authenticated:
        return redirect("fakhrialdariaskyapp:home")

    context = {
        "register_form" : RegistrationForm
    }

    if request.method == "POST":
        register_form = RegistrationForm(request.POST)
        if register_form.is_valid():
            register_form.save()
            new_user = authenticate(
                username = register_form.cleaned_data['username'],
                password = register_form.cleaned_data['password1']
            )
            new_profile = Profile.objects.create(
                user = new_user,
                full_name = new_user.username
            )
            login(request, new_user)

            return redirect("profile_view", username=new_user.username)
        elif register_form.errors:
            context["error"] = "Please enter valid a name and password."
    return render(request, "main/story9_register.html", context)


def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect("fakhrialdariaskyapp:home")

def login_view(request):
    context = {
        "login_form" : LoginForm
    }

    if request.user.is_authenticated:
        return redirect("fakhrialdariaskyapp:home")

    if request.method == "POST":
        login_form = LoginForm(data = request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            print(user.username)
            return redirect("fakhrialdariaskyapp:profile_view",username=user.username)
        elif login_form.errors:
            context["error"] = "Invalid Username or Password."
    return render(request, "main/story9_login.html", context)

def profile_view(request, username):
    user = User.objects.get(username = username)
    context = {
        "profile" : Profile.objects.get(user = user)
    }
    return render(request, "main/story9_profile.html", context)

fakhrialdariaskyapp/templates/main/home.html
{% extends 'base.html' %} {% block content %}



<div class="text-center"> 
    <img src="https://gitlab.com/aldariaski/ppw-story-7/-/raw/master/static/Foto%20JasKuning%20di%20Rotunda.PNG" width="200"  class="rounded float-center">
    <!-- Previously https://maung.id/static/5ea17d7a15e02cbcd5626d4df05b4c85/9f583/FR54.jpg
    but the website is down now.
    
    height="280" -->
    <h5> Halo {% if not request.user.is_authenticated %} kamu!</h5>
    <p> (Kamu ketahuan belum login nih hihi) </p> {% endif %} {% if request.user.is_authenticated %} {{user.username}}!</h5> {% endif %}
    <h5> Ini website Yusuf Fakhri Aldrian </h5>
    <p> Seorang pembelajar programming dari Fasilkom UI </p>
    <p class="lead"> Salam kenal! </p>
    <a class="btn btn-success" href="/story7" role="button ">
        <i class="fas fa-user"></i> Accordion (Story 7)
    </a>
    <br><br>
    <a class="btn btn-info" href="/story8" role="button ">
        <i class="fas fa-books"></i> Pustaka (Story 8)
    </a>
    <br><br>
    <h5> ~~ Story 9 ~~ </h5>
    {% if not request.user.is_authenticated %}
    <p class="lead"> Kamu belum login. Kamu bisa... </p>
    <a class="btn btn-success" href="/login" role="button ">
        <i class="fas fa-sign-in"></i> Login
    </a>
    <br><br>
    <a class="btn btn-info" href="/register" role="button ">
        <i class="fas fa-sign-in"></i> Register
    </a>{% endif %} {% if request.user.is_authenticated %}


    <p class="lead"> Kamu, {{user.username}}, sudah login! Kamu bisa....</p>
    <a class="btn btn-secondary" href="/profile/{{user.username}}" role="button ">
        <i class="fas fa-user"></i> Ke profil
    </a>
    <br><br>
    <a class="btn btn-danger" href="/logout" role="button ">
        <i class="fas fa-sign-out"></i> Logout
    </a> {% endif %}
</div>


{% endblock %}

fakhrialdariaskyapp/templates/main/story7.html
{% extends 'base.html' %} {% load static %} {% block content %}
<h1>Story 7 - Accordion</h1>
<div id="accordion" class="mx-auto my-auto" style="max-width:30rem">
    <div class="group shadow-lg">
        <h3 class="bg-primary text-light pb-3" style="font-size:1.5rem">
            Introduction
            <button type="button" class="btn btn-success btn-sm mx-1 py-0 float-right down" id="down">↓</button>
            <button type="button" class="btn btn-success btn-sm mx-1 py-0 float-right up" id="up">↑</button>
        </h3>
        <div>Hi, I am Yusuf Fakhri Aldrian. I am a computer science student at Fasilkom UI.</div>
    </div>
    <div class="group shadow-lg">
        <h3 class="bg-primary text-light pb-3" style="font-size:1.5rem">
            Showcase
            <button type="button" class="btn btn-success btn-sm mx-1 py-0 float-right down" id="down">↓</button>
            <button type="button" class="btn btn-success btn-sm mx-1 py-0 float-right up" id="up">↑</button>
        </h3>
        <div><img src="https://i.redd.it/7viz67fcfs261.png" height=200px alt=""> Some art I did.</div>
    </div>
    <div class="group shadow-lg">
        <h3 class="bg-primary text-light pb-3" style="font-size:1.5rem">
            Skills
            <button type="button" class="btn btn-success btn-sm mx-1 py-0 float-right down" id="down">↓</button>
            <button type="button" class="btn btn-success btn-sm mx-1 py-0 float-right up" id="up">↑</button>
        </h3>
        <div>-Python<br>-Java<br>-Django Web Development<br>-PHP<br>-Adobe Illustrator
        </div>
    </div>
    <div class="group shadow-lg">
        <h3 class="bg-primary text-light pb-3" style="font-size:1.5rem">
            Message to you
            <button type="button" class="btn btn-success btn-sm mx-1 py-0 float-right down" id="down">↓</button>
            <button type="button" class="btn btn-success btn-sm mx-1 py-0 float-right up" id="up">↑</button>
        </h3>
        <div>Have fun dan tetap semangat! <i class="fal fa-grin-squint"></i></div>
    </div>
</div>


<script src="{% static 'js/accordion.js' %}"></script>
<br><br>{% endblock content %}

fakhrialdariaskyapp/templates/main/story8.html
{% extends 'base.html' %} {% load static %} {% block content %}



<div class="text-center ">
    <h1> Pustaka </h1>
    <h5> Cari buku yang Anda butuhkan. </h5>
    <p class="lead"> Didukung oleh <a href="https://www.googleapis.com/books/v1/volumes?q=">GoogleApi</a> dan Ajax</p>
    <div class="d-flex justify-content-center">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" id="search-query" style="width: 18rem;">
        <button class="btn btn-outline-success my-2 my-sm-0" id="search" style="width: 5rem;">Search</button>
    </div>

</div>

<div class="d-flex flex-column" id="hasilSearch">
</div>

<script src="{% static 'js/search.js' %}"></script>
{% endblock %}

fakhrialdariaskyapp/templates/main/story9_login.html
{% extends 'base.html' %} {% load static %} {% block content %}
<h1>Login</h1>
<div class="alert alert-info alert-dismissible fade show" role="alert">
    <strong>Kamu bisa gunakan ini</strong><br/>
    <strong>User:</strong> senang.ppw<br/>
    <strong>Password:</strong> xaCw7g@Y@%rSDMBy
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
</div>
{% if error %}
<p class="text-center p-2 bg-danger rounded-lg">{{error}}</p>
{% endif %}
<form method="POST" action="{% url 'fakhrialdariaskyapp:login_view' %}" class="login-form p-4">
    {% csrf_token %} {{login_form}}
    <button type="submit" id="btn_login" class="btn btn-success">Login</button>
</form>
<p>Belum punya akun? <a href="{% url 'fakhrialdariaskyapp:register_view' %}">Register disini</a>.</p>
<br><br>{% endblock content %}

fakhrialdariaskyapp/templates/main/story9_profile.html
{% extends 'base.html' %} {% load static %} {% block content %}
<h1>Profil {{profile.user.username}}</h1>
<img class="profile-img rounded mx-auto d-block float-right" src="{{profile.profile_picture_url}}" height="120">

<p>Hi {{user.username}}!</p>

<div id="container" class="text-dark">
    <p class="lead">Notes dari {{profile.user.username}}:</p>
    {{profile.description}}
</div>

<br><br>{% endblock content %}

fakhrialdariaskyapp/templates/main/story9_register.html
{% extends 'base.html' %} {% load static %} {% block content %}
<h1>Register</h1>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>Requirement password</strong> Lebih dari 8 karakter serta mempunyai alfabet, angka, dan simbol.
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
</div>
{% if error %}
<p class="text-center p-2 bg-danger rounded-lg">{{error}}</p>
{% endif %}
<form method="POST" action="{% url 'fakhrialdariaskyapp:register_view' %}" class="login-form p-4">
    {% csrf_token %} {{register_form}}
    <button type="submit" id="btn_register" class="btn btn-success">Register</button>
</form>
<p>Sudah punya akun? <a href="{% url 'fakhrialdariaskyapp:login_view' %}">Login disini</a>.</p>
<br><br>{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <title>Yusuf Fakhri Aldrian's site
    </title>
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha512-mSYUmp1HYZDFaVKK//63EcZq4iFWFjxSL+Z3T/aCt4IO9Cejm03q3NKKYN6pFQzY0SBOr8h+eCIAZHPXcpZaNw==" crossorigin="anonymous"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ==" crossorigin="anonymous"></script>



    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.14.0/css/all.css">
    <link rel="stylesheet" href="https://static.fontawesome.com/css/fontawesome-app.css">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js"></script>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/alda.css' %}">
    <link rel="icon" type="image/ico" href="{% static 'img/django-logo-negative.svg' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> {% block meta %} {% endblock meta %}


</head>

<body>

    {% include 'navbar.html' %}

    <div class="container bg-light-transparent align-self-center container justify-content-center">
        <br><br><br><br>
        <h1 class="text-light">
            Fakhri's PPW
        </h1>

    </div>


    <div class="container justify-content-center">
        <div class="jumbotron bg-muted my-auto .justify-content-center">
            {% block content %} {% endblock content %}
        </div>
    </div>
    <br><br>
</body>

</html>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
    <a class="navbar-brand" href="/">
        <img src="{% static 'img/django-logo-negative.svg' %}" height=30px alt=""> Yusuf Fakhri Aldrian's PPW
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">


        <a class="navbar-brand" href="#">

        </a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="/">Beranda</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/story7">Story 7 - Accordion</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/story8">Story 8 - Pustaka</a>
            </li>
            {% if not request.user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="/login">Story 9 - Login</a>
            </li>
            {% endif %} {% if request.user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="/profile/{{user.username}}">Story 9 - Profil {{user.username}}</a>
            </li> {% endif %}
        </ul>

        <ul class="navbar-nav my-2 my-sm-0y">

            {% if not request.user.is_authenticated %}
            <li class="nav-item">
                <a class="btn btn-success" role="button" href="/login">Login</a>
            </li>
            <li class="nav-item">
                <a class="btn btn-info" role="button" href="/register">Register</a>
            </li>
            {% endif %} {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link text-light" href="/profile/{{user.username}}">{{user.username}}</a>
            </li>
            <li class="nav-item">
                <a class="btn btn-danger" role="button" href="/logout">Logout</a>
            </li> {% endif %}

        </ul>

    </div>
</nav>